<?php
/** Purpose-specific OSCA fields used by the application editing modal. */
$prefix = $formFieldPrefix ?? '';
$id = static fn(string $name): string => $prefix . $name;
?>

<div class="form-section">
    <h3><i class="fas fa-address-card"></i> Official Form Profile</h3>
    <div class="form-row">
        <div class="form-group">
            <label for="<?php echo $id('placeOfBirth'); ?>">Place of Birth</label>
            <input type="text" id="<?php echo $id('placeOfBirth'); ?>" name="placeOfBirth">
        </div>
        <div class="form-group">
            <label for="<?php echo $id('nationality'); ?>">Nationality</label>
            <input type="text" id="<?php echo $id('nationality'); ?>" name="nationality">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label for="<?php echo $id('gender'); ?>">Gender</label>
            <select id="<?php echo $id('gender'); ?>" name="gender">
                <option value="">Select gender</option><option value="Male">Male</option><option value="Female">Female</option>
                <option value="Other">Other</option><option value="Prefer not to say">Prefer not to say</option>
            </select>
        </div>
        <div class="form-group">
            <label for="<?php echo $id('civilStatus'); ?>">Civil Status</label>
            <select id="<?php echo $id('civilStatus'); ?>" name="civilStatus">
                <option value="">Select status</option><option value="Single">Single</option><option value="Married">Married</option>
                <option value="Widowed">Widowed</option><option value="Separated">Separated</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="<?php echo $id('seniorIdNo'); ?>">Senior Citizen ID No.</label>
        <input type="text" id="<?php echo $id('seniorIdNo'); ?>" name="seniorIdNo" readonly
               placeholder="Assigned by OSCA after Senior ID approval">
        <small class="form-hint">This official number is generated by OSCA and cannot be edited here.</small>
    </div>
</div>

<div id="<?php echo $id('senior-fields'); ?>" class="form-section osca-type-fields" style="display:none;">
    <h3><i class="fas fa-id-card"></i> Senior ID Registration</h3>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('idPurpose'); ?>">Application Purpose</label><select id="<?php echo $id('idPurpose'); ?>" name="idPurpose"><option value="">Select purpose</option><option value="new">New / First-time</option><option value="lost">Lost ID Replacement</option><option value="change">Information Change</option><option value="transfer">Transfer</option></select></div>
        <div class="form-group"><label for="<?php echo $id('controlNo'); ?>">Control Number</label><input type="text" id="<?php echo $id('controlNo'); ?>" name="controlNo"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('idTypePresented'); ?>">ID Type Presented</label><input type="text" id="<?php echo $id('idTypePresented'); ?>" name="idTypePresented"></div>
        <div class="form-group"><label for="<?php echo $id('tin'); ?>">TIN</label><input type="text" id="<?php echo $id('tin'); ?>" name="tin"></div>
    </div>
    <div class="form-group"><label for="<?php echo $id('healthStatus'); ?>">Health Status</label><textarea id="<?php echo $id('healthStatus'); ?>" name="healthStatus" rows="2"></textarea></div>
</div>

<div id="<?php echo $id('landbank-fields'); ?>" class="form-section osca-type-fields" style="display:none;">
    <h3><i class="fas fa-building-columns"></i> Land Bank Enrollment</h3>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('nameOnCard'); ?>">Name on Card</label><input type="text" id="<?php echo $id('nameOnCard'); ?>" name="nameOnCard"></div>
        <div class="form-group"><label for="<?php echo $id('mothersMaidenName'); ?>">Mother's Maiden Name</label><input type="text" id="<?php echo $id('mothersMaidenName'); ?>" name="mothersMaidenName"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('tin'); ?>-bank">TIN</label><input type="text" id="<?php echo $id('tin'); ?>-bank" name="tin" data-populate-field="tin"></div>
        <div class="form-group"><label for="<?php echo $id('idTypePresented'); ?>-bank">ID Type Presented</label><input type="text" id="<?php echo $id('idTypePresented'); ?>-bank" name="idTypePresented" data-populate-field="idTypePresented"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('landbankCardNo'); ?>">Cash Card Number</label><input type="text" id="<?php echo $id('landbankCardNo'); ?>" name="landbankCardNo"></div>
        <div class="form-group"><label for="<?php echo $id('atmCardNo'); ?>">ATM / Temporary Stub No.</label><input type="text" id="<?php echo $id('atmCardNo'); ?>" name="atmCardNo"></div>
    </div>
    <div class="form-group"><label for="<?php echo $id('sourceOfFunds'); ?>">Source of Funds</label><input type="text" id="<?php echo $id('sourceOfFunds'); ?>" name="sourceOfFunds"></div>
</div>

<div id="<?php echo $id('pension-extra-fields'); ?>" class="form-section osca-type-fields" style="display:none;">
    <h3><i class="fas fa-coins"></i> Pension and Household Assessment</h3>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('isPensioner'); ?>">Currently a Pensioner?</label><select id="<?php echo $id('isPensioner'); ?>" name="isPensioner"><option value="">Select</option><option value="1">Yes</option><option value="0">No</option></select></div>
        <div class="form-group"><label for="<?php echo $id('pensionSource'); ?>">Pension Source</label><input type="text" id="<?php echo $id('pensionSource'); ?>" name="pensionSource"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('isPermanentIncome'); ?>">Permanent Income?</label><select id="<?php echo $id('isPermanentIncome'); ?>" name="isPermanentIncome"><option value="">Select</option><option value="1">Yes</option><option value="0">No</option></select></div>
        <div class="form-group"><label for="<?php echo $id('incomeSource'); ?>">Income Source</label><input type="text" id="<?php echo $id('incomeSource'); ?>" name="incomeSource"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('personalIncome'); ?>">Personal Income?</label><select id="<?php echo $id('personalIncome'); ?>" name="personalIncome"><option value="">Select</option><option value="1">Yes</option><option value="0">No</option></select></div>
        <div class="form-group"><label for="<?php echo $id('personalIncomeAmount'); ?>">Personal Income Amount</label><input type="number" min="0" step="0.01" id="<?php echo $id('personalIncomeAmount'); ?>" name="personalIncomeAmount"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('familySupport'); ?>">Family Support?</label><select id="<?php echo $id('familySupport'); ?>" name="familySupport"><option value="">Select</option><option value="1">Yes</option><option value="0">No</option></select></div>
        <div class="form-group"><label for="<?php echo $id('familySupportAmount'); ?>">Family Support Amount</label><input type="number" min="0" step="0.01" id="<?php echo $id('familySupportAmount'); ?>" name="familySupportAmount"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('ownsHouse'); ?>">Owns House?</label><select id="<?php echo $id('ownsHouse'); ?>" name="ownsHouse"><option value="">Select</option><option value="1">Yes</option><option value="0">No</option></select></div>
        <div class="form-group"><label for="<?php echo $id('isRenter'); ?>">Renter?</label><select id="<?php echo $id('isRenter'); ?>" name="isRenter"><option value="">Select</option><option value="1">Yes</option><option value="0">No</option></select></div>
    </div>
</div>

<div id="<?php echo $id('milestone-fields'); ?>" class="form-section osca-type-fields" style="display:none;">
    <h3><i class="fas fa-cake-candles"></i> Milestone Gift Claim</h3>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('milestoneAge'); ?>">Milestone Age</label><select id="<?php echo $id('milestoneAge'); ?>" name="milestoneAge"><option value="">Select milestone</option><option value="80">80 years old</option><option value="85">85 years old</option><option value="90">90 years old</option><option value="95">95 years old</option><option value="100">100+ years old</option></select></div>
        <div class="form-group"><label for="<?php echo $id('applicantName'); ?>">Applicant Name</label><input type="text" id="<?php echo $id('applicantName'); ?>" name="applicantName"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('claimantName'); ?>">Claimant Name</label><input type="text" id="<?php echo $id('claimantName'); ?>" name="claimantName"></div>
        <div class="form-group"><label for="<?php echo $id('claimantRelationship'); ?>">Relationship</label><input type="text" id="<?php echo $id('claimantRelationship'); ?>" name="claimantRelationship"></div>
    </div>
    <div class="form-group"><label for="<?php echo $id('claimantContact'); ?>">Claimant Contact</label><input type="text" id="<?php echo $id('claimantContact'); ?>" name="claimantContact"></div>
</div>

<div id="<?php echo $id('burial-extra-fields'); ?>" class="form-section osca-type-fields" style="display:none;">
    <h3><i class="fas fa-ribbon"></i> Deceased Senior and Claimant</h3>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('deceasedFirstName'); ?>">Deceased First Name</label><input type="text" id="<?php echo $id('deceasedFirstName'); ?>" name="deceasedFirstName"></div>
        <div class="form-group"><label for="<?php echo $id('deceasedMiddleName'); ?>">Deceased Middle Name</label><input type="text" id="<?php echo $id('deceasedMiddleName'); ?>" name="deceasedMiddleName"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('deceasedLastName'); ?>">Deceased Last Name</label><input type="text" id="<?php echo $id('deceasedLastName'); ?>" name="deceasedLastName"></div>
        <div class="form-group"><label for="<?php echo $id('deceasedSuffix'); ?>">Suffix</label><input type="text" id="<?php echo $id('deceasedSuffix'); ?>" name="deceasedSuffix"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('deceasedBirthDate'); ?>">Deceased Birth Date</label><input type="date" id="<?php echo $id('deceasedBirthDate'); ?>" name="deceasedBirthDate"></div>
        <div class="form-group"><label for="<?php echo $id('applicantName'); ?>-burial">Applicant / Claimant Name</label><input type="text" id="<?php echo $id('applicantName'); ?>-burial" name="applicantName" data-populate-field="applicantName"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('claimantName'); ?>-burial">Claimant Name</label><input type="text" id="<?php echo $id('claimantName'); ?>-burial" name="claimantName" data-populate-field="claimantName"></div>
        <div class="form-group"><label for="<?php echo $id('claimantContact'); ?>-burial">Claimant Contact</label><input type="text" id="<?php echo $id('claimantContact'); ?>-burial" name="claimantContact" data-populate-field="claimantContact"></div>
    </div>
</div>

<div id="<?php echo $id('homevisit-fields'); ?>" class="form-section osca-type-fields" style="display:none;">
    <h3><i class="fas fa-house-medical"></i> Home Visit Assessment</h3>
    <div class="form-group"><label for="<?php echo $id('visitPurpose'); ?>">Visit Purpose</label><input type="text" id="<?php echo $id('visitPurpose'); ?>" name="visit_purpose"></div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('livingArrangement'); ?>">Living Arrangement</label><input type="text" id="<?php echo $id('livingArrangement'); ?>" name="livingArrangement"></div>
        <div class="form-group"><label for="<?php echo $id('healthCondition'); ?>">Health Condition</label><input type="text" id="<?php echo $id('healthCondition'); ?>" name="healthCondition"></div>
    </div>
    <div class="form-row">
        <div class="form-group"><label for="<?php echo $id('withMaintenance'); ?>">Maintenance Medicine?</label><select id="<?php echo $id('withMaintenance'); ?>" name="withMaintenance"><option value="">Select</option><option value="1">Yes</option><option value="0">No</option></select></div>
        <div class="form-group"><label for="<?php echo $id('maintenanceSpec'); ?>">Medicine Details</label><input type="text" id="<?php echo $id('maintenanceSpec'); ?>" name="maintenanceSpec"></div>
    </div>
    <div class="form-group"><label for="<?php echo $id('visitSummary'); ?>">Visit Summary</label><textarea id="<?php echo $id('visitSummary'); ?>" name="visitSummary" rows="3"></textarea></div>
</div>
