// Run against the isolated server started by workflow.integration.cjs --serve.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    const context = await browser.newContext({ viewport: { width: 1365, height: 1000 } });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') console.log('Browser:', message.text()); });
    const base = 'http://127.0.0.1:8765';
    await page.goto(base + '/index.php');
    await page.locator('#trackLink').click();
    const landingToken = page.locator('#landingTrackerToken');
    assert.equal(await landingToken.inputValue(), 'PRX-');
    await landingToken.fill('7k2m');
    assert.equal(await landingToken.inputValue(), 'PRX-7K2M');
    await landingToken.fill('prx-prx-7k2m');
    assert.equal(await landingToken.inputValue(), 'PRX-7K2M');
    await page.goto(base + '/pages/benefit_tracker.php?token=PRX-BENE');
    await page.locator('#token').focus();
    await page.locator('#token').press('ControlOrMeta+A');
    await page.locator('#token').pressSequentially('bene');
    assert.equal(await page.locator('#token').inputValue(), 'PRX-BENE');
    console.log('PASS Track Application prefills PRX-, uppercases manual entry, and accepts pasted tokens.');
    await context.request.post(base + '/index.php', { form: { login_role: 'department_admin', username: 'test-admin', password: 'TestOnly!2026' } });
    await page.goto(base + '/pages/department_dashboard.php');
    assert.equal(await page.locator('.attention-panel').count(), 0);
    await page.goto(base + '/pages/department_records.php?application=VALID');
    await page.locator('#releaseScheduleSection').waitFor({ state: 'visible' });
    assert.ok(await page.getByLabel('Expected release date').isVisible());
    await page.getByLabel('Expected release date').fill('2000-01-01');
    await page.getByRole('button', { name: 'Save expected date' }).click();
    await page.locator('#releaseDateError').filter({ hasText: 'Choose today or a future date' }).waitFor();
    const releaseDate = new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10);
    await page.getByLabel('Expected release date').fill(releaseDate);
    await page.getByRole('button', { name: 'Save expected date' }).click();
    await page.locator('#releaseDateStatus').filter({ hasText: 'Expected release date set' }).waitFor();
    assert.equal((await (await context.request.get(base + '/api/get_application_details.php?id=VALID')).json()).expected_release_date, releaseDate);
    await page.getByRole('button', { name: 'Remove date' }).click();
    await page.locator('.carelink-confirm-ok').click();
    await page.locator('#releaseDateStatus').filter({ hasText: 'Expected release date removed' }).waitFor();
    console.log('PASS Department Records can validate, save, and remove the expected release date.');
    await page.goto(base + '/pages/verify_document.php?application=UI-CORRECTION');
    await page.locator('#statusInstructions').filter({ hasText: 'Waiting for barangay' }).waitFor();
    assert.equal(await page.locator('#btnAdvanceStatus').isVisible(), false);
    await page.locator('#dynamicDetailsSection').filter({ hasText: 'PSA birth certificate' }).waitFor();
    console.log('PASS Department correction view shows the correct actions and reason.');
    const staffContext = await browser.newContext({ viewport: { width: 1365, height: 1000 } });
    const staffPage = await staffContext.newPage();
    staffPage.on('pageerror', error => errors.push(error.message));
    staffPage.on('console', message => { if (message.type() === 'error') console.log('Staff browser:', message.text()); });
    await staffContext.request.post(base + '/index.php', { form: { login_role: 'barangay_staff', username: 'test-staff', password: 'TestOnly!2026', barangay: 'Bagong Ilog' } });
    await staffPage.goto(base + '/pages/barangay_dash.php');
    assert.equal(await staffPage.locator('.attention-panel').count(), 0);
    await staffPage.goto(base + '/pages/submit_application.php?application=UI-CORRECTION');
    await staffPage.locator('#returnedWarningBox').waitFor();
    assert.match(await staffPage.locator('#returnedReasonText').innerText(), /PSA birth certificate/);
    await staffPage.getByRole('button', { name: /Submit to Review Desk/ }).waitFor({timeout:5000});
    assert.ok(await staffPage.getByRole('button', { name: 'Save document', exact: true }).isVisible());
    console.log('PASS Barangay correction view supports resubmission and missing-document controls.');
    // Exercise browser upload, resubmission, and dashboard removal on a synthetic application.
    await staffPage.locator('.missing-document-label').fill('PSA birth certificate');
    await staffPage.locator('.missing-document-label').locator('..').locator('..').locator('input[type=file]').setInputFiles({ name: 'corrected.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n% Browser test document\n%%EOF') });
    await staffPage.getByRole('button', { name: 'Save document', exact: true }).click();
    await staffPage.locator('.application-document__name').filter({ hasText: 'PSA birth certificate' }).waitFor();
    console.log('PASS Missing correction document is uploaded and displayed in the browser.');
    await staffPage.locator('#carelinkResultModal .carelink-result-ok').click();
    await staffPage.getByRole('button', { name: /Submit to Review Desk/ }).click();
    await Promise.all([staffPage.waitForResponse(response => response.url().includes('update_workflow_status.php') && response.status() === 200), staffPage.locator('.carelink-confirm-ok').click()]);
    const resubmitted = await (await staffContext.request.get(base + '/api/get_application_details.php?id=UI-CORRECTION')).json();
    assert.equal(resubmitted.workflow_state, 'For Review');
    assert.equal(resubmitted.return_reason, null);
    console.log('PASS Browser resubmission moves the corrected application back to review.');
    const publicContext = await browser.newContext();
    const publicPage = await publicContext.newPage();
    publicPage.on('pageerror', error => errors.push(error.message));
    await publicPage.goto(base + '/pages/proxy_registration.php');
    assert.equal(await publicPage.locator('button[onclick="verifySeniorID()"]').count(), 0);
    console.log('PASS Public form no longer offers personal-data lookup.');
    assert.deepEqual(errors, [], 'Browser JavaScript errors');
    console.log('PASS No browser JavaScript errors.');
    await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
